package com.kpisoft.kpi.vo.param;

public enum WorkflowParams
{
    SCORECARD_ID, 
    SCORECARD_STATE, 
    EMP_ID, 
    USER_ID, 
    COMMENTS, 
    IS_APPROVED, 
    GOAL_COMMENTS_ID, 
    GOAL_COMMENTS_DATA, 
    GOAL_COMMENTS_DATA_LIST, 
    SCORE_ID, 
    SCORE_STATE, 
    PERFORMANCE_COMMENTS_ID, 
    PERFORMANCE_COMMENTS_DATA, 
    PERFORMANCE_COMMENTS_DATA_LIST, 
    STATUS, 
    ENTITY_ID, 
    WORK_FLOW_TASK_LIST, 
    WORK_FLOW_TYPE, 
    EXPRESSION, 
    NAME, 
    WORKFLOW_LEVELS, 
    SCORECARDSUBMIT, 
    SCORESUBMIT, 
    COUNT, 
    ORG_ID, 
    USER_SCORECARD_MAP;
}
