package com.kpisoft.org.utility;

public enum OrgErrorCodesEnum
{
    ERR_GRD_UNKNOWN_EXCEPTION_000, 
    ERR_GRD_DOES_NOT_EXIST_001, 
    ERR_GRD_INVALID_INPUT_002, 
    ERR_GRD_UNABLE_TO_CREATE_003, 
    ERR_GRD_UNABLE_TO_GET_004, 
    ERR_GRD_UNABLE_TO_UPDATE_005, 
    ERR_GRD_UNABLE_TO_DELETE_006, 
    ERR_GRD_UNABLE_TO_GET_ALL_007, 
    ERR_GRD_UNABLE_TO_SEARCH_008;
}
